# apiVersion: apps/v1 
# kind: Deployment
# metadata:
#   name: web-deployment
#   namespace: default
# spec:
#   selector:
#     matchLabels:
#       app: web
#   replicas: 3 # tells deployment to run 3 pods matching the template
#   template:
#     metadata:
#       labels:
#         app: web
#     spec:
#       containers:
#       - name: devops-webapp
#         image: rush1898/web-server-image:v1
#         ports:
#         - containerPort: 80
